baseurl = "https://www.wakingupthenetwork.com/"
title = "Waking up the Network"
theme = "hugo-universal-theme"
languageCode = "en-us"

# Site language. Available translations in the theme's `/i18n` directory.
defaultContentLanguage = "en"

# Enable Google Analytics by entering your tracking code
googleAnalytics = "G-ZXQE4SYH7P"

[menu]

# Main menu

[[menu.main]]
    identifier="home"
    name = "Home"
    url  = "/"
    weight = 1

[[menu.main]]
    identifier="privacy"
    name = "Privacy Policy"
    url  = "/privacy/"
    weight = 2

[params]
    # Style options: default (light-blue), blue, green, marsala, pink, red, turquoise, violet
    style = "red"

    about_us = "<p>Developed by Neale Lonslow, an independent sole developer based in the UK writing applications to help home users, system administrators and infrastructure experts.</p>"
    copyright = "Copyright (c) 2021, Neale Lonslow; all rights reserved."

    # Format dates with Go's time formatting
    date_format = "January 2, 2006"

    site_title = "Waking Up the Network"

#    formspree_action = "https://formspree.io/f/mqkwldwv"
#    contact_form_ajax = false

[params.testimonials]
    enable = true
    title = "Reviews"

[params.carousel]
    enable = true

[params.features]
    enable = true
    
[params.see_more]
    enable = true
    icon = "fab fa-windows"
    title = "Try / Purchase"
    subtitle = "Install the Free Trial, or buy the Full Product on the Windows Store now."
    link_url = "https://www.microsoft.com/store/apps/9N0MNLDX6K2N"
    link_text = "Visit the Store !"

[params.recent_posts]
    enable = true
    title = "Waking Up the Network"
    subtitle = "A Windows application that sends Wake-On-LAN packets (sometimes known as magic packets) to the MAC addresses of devices to turn them on. The application allows devices to be organised into groups so they can all be woken up at once."
    subtitle2 = "The application is only available via the Windows Store, and an add-on is available that enables the features to allow for Network Discovery and Active Directory integration. These features save time - run Network Discovery when the devices are turned on and immediately import them into the application. Or organise domain-joined computers into an Active Directory group and import the group into the application so all can be awoken at the same time."

#[params.contact]
#    content = "Send us a message with your questions, thoughts or feedback !"
#    icon = "far fa-envelope"
